const permissionsObj = { 
    VIEW_USERS: 'view users',
    EDIT_USERS: 'edit users',
    DELETE_USERS: 'delete users',
    DELETE_APOSTLE_DESK_MESSAGE: 'delete apostle desk message',
    CREATE_APOSTLE_DESK_MESSAGE: 'create apostle desk message',
    EDIT_APOSTLE_DESK_MESSAGE: 'edit apostle desk message',
    PUBLISH_APOSTLE_DESK_MESSAGE: 'publish apostle desk message',
    PUBLISH_PRAYER: 'publish prayer',
    CREATE_PRAYER: 'create prayer',
    EDIT_PRAYER: 'edit prayer',
    DELETE_PRAYER: 'delete prayer',
    VIEW_PRAYER: 'view prayer',
    VIEW_SERMON: 'view sermon',
    CREATE_SERMON: 'create sermon',
    EDIT_SERMON: 'edit sermon',
    DELETE_SERMON: 'delete sermon',
    PUBLISH_SERMON: 'publish sermon',
    DELETE_DAILYPRAYER: 'delete dailyprayer',
    EDIT_DAILYPRAYER: 'edit dailyprayer',
    VIEW_DAILYPRAYER: 'view dailyprayer',
    PUBLISH_DAILYPRAYER: 'publish dailyprayer',
    CREATE_DAILYPRAYER: 'create dailyprayer',
    EDIT_ADMIN: 'edit admin',
    DELETE_ADMIN: 'delete admin',
    INVITE_ADMIN: 'invite admin',
    'ACTIVATE/DEACTIVATE_ADMIN': 'activate/deactivate admin',
    VIEW_ADMIN: 'view admin',
    PUBLISH_PASTORFORUM: 'publish pastorforum',
    EDIT_PASTORFORUM: 'edit pastorforum',
    CREATE_PASTORFORUM: 'create pastorforum',
    VIEW_PASTORFORUM: 'view pastorforum',
    DELETE_PASTORFORUM: 'delete pastorforum',
    ACTIVATE_BRANCH: 'activate branch',
    CREATE_BRANCH: 'create branch',
    EDIT_BRANCH: 'edit branch',
    DELETE_BRANCH: 'delete branch',
    VIEW_BRANCH: 'view branch',
    VIEW_GROUP: 'view group',
    EDIT_GROUP: 'edit group',
    CREATE_GROUP: 'create group',
    DELETE_GROUP: 'delete group',
    'ACTIVATE/DEACTIVATE_GROUP': 'activate/deactivate group',
    VIEW_BIBLE_READING: 'view bible reading',
    CREATE_BIBLE_READING: 'create bible reading',
    EDIT_BIBLE_READING: 'edit bible reading',
    DELETE_BIBLE_READING: 'delete bible reading',
    PUBLISH_BIBLE_READING: 'publish bible reading',
    VIEW_APOSTLE_DESK_MESSAGE: 'view apostle desk message',
    EDIT_BIBLE_STUDY: 'edit bible study',
    CREATE_BIBLE_STUDY: 'create bible study',
    DELETE_BIBLE_STUDY: 'delete bible study',
    VIEW_BIBLE_STUDY: 'view bible study',
    PUBLISH_BIBLESTUDY: 'publish biblestudy',
    VIEW_APPOINTMENT: 'view appointment' 
}


export default permissionsObj; 